### ISSUE TITLE
offOnce and historical records

### ISSUE THREAD

**Issue by dpatte** [micktaiwan/meteor-vermongo#10]
I need to do a schema change on a collection and its vermongo history collection.

What it the process to disable doing a new version when I update a record, and what is the process to update a .vermongo (historical) record?

**Comment by micktaiwan** [comment]
You can just set offOnce to true just before the update

**Comment by dpatte** [comment]
yes, i noticed i can do myCollection.vermongoOffOnce(); myCollection.update(...)

and for modifying my historical records i realized they are a simple collection so nothing special has to be done to update them, and updating them has no side effects.
