### ISSUE TITLE
Feedback for enhancement

### ISSUE THREAD

**Issue by serkandurusoy** [micktaiwan/meteor-vermongo#4]
Hi,

I've been using this package for a few weeks now and I think it is the most comprehensive one that's available. So kudos for developing it!

I have significant experience (coming from the java world with solid orm layers like hibernate and spring data) with versioning and atomic updates.

I'd like to chip in, if you don't mind, and share some feedback. In fact, if we can agree on these, I may  even be able to contribute with PR's.

So here they are:
- The vermongo collection and its first document should be created at insert
- Modified timestamp should not be added on insert
- Both the existence and the names of timestamp fields (createdAt, createdBy, modifiedAt, modifiedBy) should be configurable
- A global vermongo configuration option should be provided
- An atomic [find and modify](https://github.com/fongandrew/meteor-find-and-modify/) option should be available
- Before update hook should analyze the modifier to derive the field names, instead of relying on the provided field names so that we can compare nested fields instead of just top level fields
- A collection.fetchVersion(_v) method should be available to gain direct access to versions
- A collection.restoreVersion(_v) method should be available to revert to versions
- A new orm layer called [astronomy](https://github.com/jagi/meteor-astronomy) is picking up pace and adoption. Perhaps we can support that, too.

So, what do you think? Would you like to discuss and possibly work together on implementing these?

**Comment by micktaiwan** [comment]
Hello,

Your feedback is much appreciated.
Of course I'd be happy to work together.

I will study your suggestions.
I do not know astronomy, I will take a look.

I have a daily job, so my response time will not be as fast as you could expect :)
Mickael.

**Comment by serkandurusoy** [comment]
Thanks Mickael, I'm happy that you are on board with the idea.

Don't worry about astronomy right now, it's a future step.

Take your time and let me know when you're ready to discuss this further.

Cheers

**Comment by micktaiwan** [comment]
Well, do as you want :)
Pull requests, or directly participating.

**Comment by serkandurusoy** [comment]
Great, thank you. I'll do some planning and thinking and hopefully get back to you soon.
