### ISSUE TITLE
Increased CPU usage

### ISSUE THREAD

**Issue by s7dhansh** [micktaiwan/meteor-vermongo#7]
Including the package causes a CPU usage of 100%. Is this normal? Or else, I will drill it down and attach a simple example to reproduce.

**Comment by micktaiwan** [comment]
No, never saw that.

**Comment by s7dhansh** [comment]
Found the bug:

So, whenever I try to pass an object to the subscribe function as parameter for the subscription, it goes in an endless loop. Sadly, I was unable to find it in your code. It would be awesome if you can help me.

It works if I pass literals/arrays.

Steps to reproduce:
- meteor create app
- replace app.js with following code. see browser console and server console.

```
Test = new Mongo.Collection("test").vermongo({timestamps: true, userId: 'modifierId', ignoredFields: []});

Router.configure({
  waitOn: function() { 
    console.log(11);
    return Meteor.subscribe('test', {limit: 10}); 
  }
});

Router.route('/', function () {
  this.render('hello', {
    data: function () { return Test.find({}); }
  });
});

if (Meteor.isServer) {
  Meteor.publish('test', function(options){
    console.log(options);
    return Test.find({}, {limit: options.limit});
  });
}
```

**Comment by s7dhansh** [comment]
Found the problem: Array.prototype.equals is the culprit. 

Probably it was being defined somewhere else as well (though I always got [1].equals to be undefined, both on the server and client). So frankly, I do not have a single clue. But changing the `equals` to anything else works. Request a merge.

**Comment by micktaiwan** [comment]
Thanks for your work.
I need to review the bug.
Changing the name of a function impacts all code that use it.
I'll get back to you soon.

**Comment by s7dhansh** [comment]
Sure.

I tried to change it all the places possible and tested it properly, but yes, it's your code, so please review and revert. :)
Thanks.

**Comment by s7dhansh** [comment]
Hi @micktaiwan did you get the time to check it?

**Comment by micktaiwan** [comment]
Sorry, not yet. I know it is frustrating, I'll try this week-end.

**Comment by mazing** [comment]
+1

**Comment by s7dhansh** [comment]
@mazing please check if my fork resolves it... (I simply changed Array.equals to Array.sameAs)

**Comment by micktaiwan** [comment]
I pulled your merge request. But I was not able to reproduce it.
